package com.yuti.kidnapmod.init;

import com.yuti.kidnapmod.extrainventory.ExtraBondageMaterial;
import com.yuti.kidnapmod.items.ItemBind;
import com.yuti.kidnapmod.items.ItemBindColored;
import com.yuti.kidnapmod.items.ItemBlindfold;
import com.yuti.kidnapmod.items.ItemBlindfoldColored;
import com.yuti.kidnapmod.items.ItemBondageToy;
import com.yuti.kidnapmod.items.ItemChloroformBottle;
import com.yuti.kidnapmod.items.ItemClothes;
import com.yuti.kidnapmod.items.ItemCollar;
import com.yuti.kidnapmod.items.ItemDuctTapeBind;
import com.yuti.kidnapmod.items.ItemDuctTapeGag;
import com.yuti.kidnapmod.items.ItemEarplugs;
import com.yuti.kidnapmod.items.ItemEnclosed;
import com.yuti.kidnapmod.items.ItemGag;
import com.yuti.kidnapmod.items.ItemGagColored;
import com.yuti.kidnapmod.items.ItemHood;
import com.yuti.kidnapmod.items.ItemKeyCollar;
import com.yuti.kidnapmod.items.ItemKeyCollarMaster;
import com.yuti.kidnapmod.items.ItemKidnapWearable;
import com.yuti.kidnapmod.items.ItemKnife;
import com.yuti.kidnapmod.items.ItemMedicalGag;
import com.yuti.kidnapmod.items.ItemRag;
import com.yuti.kidnapmod.items.ItemRopeArrow;
import com.yuti.kidnapmod.items.ItemShockCollar;
import com.yuti.kidnapmod.items.ItemShockCollarAuto;
import com.yuti.kidnapmod.items.ItemShockerController;
import com.yuti.kidnapmod.items.ItemStraitJacket;
import com.yuti.kidnapmod.items.ItemTrappedBed;
import com.yuti.kidnapmod.items.ItemWrap;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.item.EnumDyeColor;
import net.minecraft.item.Item;

public class ModItems {
   public static final List<Item> ITEMS = new ArrayList();
   public static final List<ItemKidnapWearable> WEARABLE = new ArrayList();
   public static final List<ItemKnife> KNIFES_LIST = new ArrayList();
   public static final List<ItemBind> BIND_LIST = new ArrayList();
   public static final List<ItemGag> GAG_LIST = new ArrayList();
   public static final List<ItemBlindfold> BLINDFOLD_LIST = new ArrayList();
   public static final List<ItemEarplugs> EARPLUGS_LIST = new ArrayList();
   public static final List<ItemCollar> COLLAR_LIST = new ArrayList();
   public static final List<ItemClothes> CLOTHES_LIST = new ArrayList();
   public static final ItemGag CLOTH_GAG;
   public static final ItemBind ROPES;
   public static final ItemGag ROPES_GAG;
   public static final ItemBind SHIBARI_ROPES;
   public static final ItemGag BALL_GAG;
   public static final ItemGag BALL_GAG_STRAP;
   public static final ItemBind STRAITJACKET;
   public static final ItemGag PANEL_GAG;
   public static final ItemBind LATEX_SACK;
   public static final ItemGag LATEX_GAG;
   public static final ItemBind WRAP;
   public static final ItemGag WRAP_GAG;
   public static final ItemBind TAPE;
   public static final ItemGag TAPE_GAG;
   public static final ItemGag CHAIN_PANEL_GAG;
   public static final ItemBind CHAIN;
   public static final ItemGag RIBBON_GAG;
   public static final ItemBind RIBBON;
   public static final ItemGag SLIME_GAG;
   public static final ItemBind SLIME;
   public static final ItemBind LEATHER_STRAPS;
   public static final ItemGag MEDICAL_GAG;
   public static final ItemBind MEDICAL_STRAPS;
   public static final ItemGag TUBE_GAG;
   public static final ItemGag VINE_GAG;
   public static final ItemBind VINE_SEED;
   public static final ItemGag BITE_GAG;
   public static final ItemBind ARMBINDER;
   public static final ItemGag WEB_GAG;
   public static final ItemBind WEB_BIND;
   public static final ItemGag BEAM_PANEL_GAG;
   public static final ItemBind BEAM_CUUFS;
   public static final ItemGag CLEAVE_GAG;
   public static final ItemGag BAGUETTE_GAG;
   public static final ItemGag SPONGE_GAG;
   public static final ItemBlindfold CLASSIC_BLINDFOLD;
   public static final ItemBlindfold MASK_BLINDFOLD;
   public static final ItemBlindfold CLASSIC_HOOD;
   public static final ItemEarplugs CLASSIC_EARPLUGS;
   public static final ItemCollar CLASSIC_COLLAR;
   public static final ItemCollar SHOCK_COLLAR;
   public static final ItemShockCollarAuto SHOCK_COLLAR_AUTO;
   public static final Item IRON_KNIFE;
   public static final Item STONE_KNIFE;
   public static final Item GOLD_KNIFE;
   public static final Item ROPE_ARROW;
   public static final ItemKeyCollar COLLAR_KEY;
   public static final ItemKeyCollar MASTER_COLLAR_KEY;
   public static final Item SHOCKER_CONTROLLER;
   public static final Item TRAPPED_BED;
   public static final Item RAG;
   public static final Item CHLOROFORM_BOTTLE;
   public static final Item PADDLE;
   public static final Item WHIP;
   public static final ItemClothes CLOTHES;

   static {
      CLOTH_GAG = new ItemGagColored("cloth_gag", ExtraBondageMaterial.GAG_CLASSIC, EnumDyeColor.WHITE);
      ROPES = new ItemBindColored("ropes", ExtraBondageMaterial.ROPES, 150, 25, EnumDyeColor.BROWN);
      ROPES_GAG = new ItemGagColored("ropes_gag", ExtraBondageMaterial.SHIBARI, EnumDyeColor.BROWN);
      SHIBARI_ROPES = new ItemBindColored("shibari", ExtraBondageMaterial.SHIBARI, 200, 25, EnumDyeColor.BROWN);
      BALL_GAG = new ItemGagColored("ball_gag", ExtraBondageMaterial.BALLGAG, EnumDyeColor.RED);
      BALL_GAG_STRAP = new ItemGagColored("ball_gag_strap", ExtraBondageMaterial.BALLGAG_STRAP, EnumDyeColor.RED);
      STRAITJACKET = new ItemStraitJacket("straitjacket", ExtraBondageMaterial.STRAITJACKET, 250, 25);
      PANEL_GAG = new ItemGag("panel_gag", ExtraBondageMaterial.GAG_PANEL);
      LATEX_SACK = new ItemEnclosed("latex_sack", ExtraBondageMaterial.LATEX, 400, 25);
      LATEX_GAG = new ItemGag("latex_gag", ExtraBondageMaterial.LATEX);
      WRAP = new ItemWrap("wrap", ExtraBondageMaterial.WRAP, 150, 25);
      WRAP_GAG = new ItemGag("wrap_gag", ExtraBondageMaterial.WRAP);
      TAPE = new ItemDuctTapeBind("duct_tape", ExtraBondageMaterial.TAPE, 100, 25);
      TAPE_GAG = new ItemDuctTapeGag("tape_gag", ExtraBondageMaterial.TAPE);
      CHAIN_PANEL_GAG = new ItemGag("chain_panel_gag", ExtraBondageMaterial.CHAIN);
      CHAIN = new ItemBind("chain", ExtraBondageMaterial.CHAIN, 500, 25);
      RIBBON_GAG = new ItemGag("ribbon_gag", ExtraBondageMaterial.RIBBON);
      RIBBON = new ItemBind("ribbon", ExtraBondageMaterial.RIBBON, 50, 25);
      SLIME_GAG = new ItemGag("slime_gag", ExtraBondageMaterial.SLIME);
      SLIME = new ItemBind("slime", ExtraBondageMaterial.SLIME, 150, 25);
      LEATHER_STRAPS = new ItemBind("leather_straps", ExtraBondageMaterial.STRAPS, 200, 25);
      MEDICAL_GAG = new ItemMedicalGag("medical_gag", ExtraBondageMaterial.MEDICAL_STRAPS);
      MEDICAL_STRAPS = new ItemBind("medical_straps", ExtraBondageMaterial.MEDICAL_STRAPS, 250, 25);
      TUBE_GAG = new ItemGag("tube_gag", ExtraBondageMaterial.TUBE);
      VINE_GAG = new ItemGag("vine_gag", ExtraBondageMaterial.VINE);
      VINE_SEED = new ItemBind("vine_seed", ExtraBondageMaterial.VINE, 150, 25);
      BITE_GAG = new ItemGag("bite_gag", ExtraBondageMaterial.BITE_GAG);
      ARMBINDER = new ItemBind("armbinder", ExtraBondageMaterial.ARM_BINDER, 200, 25);
      WEB_GAG = new ItemGag("web_gag", ExtraBondageMaterial.WEB);
      WEB_BIND = new ItemBind("web_bind", ExtraBondageMaterial.WEB, 150, 25);
      BEAM_PANEL_GAG = new ItemGag("beam_panel_gag", ExtraBondageMaterial.BEAM);
      BEAM_CUUFS = new ItemBind("beam_cuffs", ExtraBondageMaterial.BEAM, 250, 25);
      CLEAVE_GAG = new ItemGagColored("cleave_gag", ExtraBondageMaterial.CLEAVE_GAG, EnumDyeColor.WHITE);
      BAGUETTE_GAG = new ItemGag("baguette_gag", ExtraBondageMaterial.BAGUETTE_GAG);
      SPONGE_GAG = new ItemGag("sponge_gag", ExtraBondageMaterial.SPONGE_GAG);
      CLASSIC_BLINDFOLD = new ItemBlindfoldColored("blindfold_cloth", ExtraBondageMaterial.CLASSIC_BLINDFOLD, EnumDyeColor.BLACK);
      MASK_BLINDFOLD = new ItemBlindfoldColored("blindfold_mask", ExtraBondageMaterial.MASK_BLINDFOLD, EnumDyeColor.BLACK);
      CLASSIC_HOOD = new ItemHood("hood", ExtraBondageMaterial.CLASSIC_HOOD);
      CLASSIC_EARPLUGS = new ItemEarplugs("earplugs", ExtraBondageMaterial.CLASSIC_EARPLUGS);
      CLASSIC_COLLAR = new ItemCollar("collar", ExtraBondageMaterial.CLASSIC_COLLAR, 200, 25);
      SHOCK_COLLAR = new ItemShockCollar("shock_collar", ExtraBondageMaterial.SHOCK_COLLAR, 300, 25);
      SHOCK_COLLAR_AUTO = new ItemShockCollarAuto("shock_collar_auto", ExtraBondageMaterial.SHOCK_COLLAR, 0, 60, 25);
      IRON_KNIFE = new ItemKnife("iron_knife", 40);
      STONE_KNIFE = new ItemKnife("stone_knife", 5);
      GOLD_KNIFE = new ItemKnife("golden_knife", 100);
      ROPE_ARROW = new ItemRopeArrow("rope_arrow");
      COLLAR_KEY = new ItemKeyCollar("collar_key");
      MASTER_COLLAR_KEY = new ItemKeyCollarMaster("master_collar_key");
      SHOCKER_CONTROLLER = new ItemShockerController("shocker_controller");
      TRAPPED_BED = new ItemTrappedBed("trapped_bed");
      RAG = new ItemRag("rag");
      CHLOROFORM_BOTTLE = new ItemChloroformBottle("chloroform_bottle");
      PADDLE = new ItemBondageToy("paddle", 1, KidnapModSoundEvents.SLAP);
      WHIP = new ItemBondageToy("whip", 1, KidnapModSoundEvents.WHIP);
      CLOTHES = new ItemClothes("clothes", ExtraBondageMaterial.CLOTHES);
   }
}
